## 특징

* 벡터 및 행렬 연산과 관련된 편리한 기능을 제공(선형대수 관련)
* 리스트에 비해 빠르고 메모리를 효율적으로 사용
* 반복문 없이 데이터 배열에 대한 처리를 지원(인덱싱, 질의)
* http://www.numpy.org
* ndarray(여러차원의 배열) 기본 데이터 타입 사용 

In [2]:
import numpy as np

## 1차원 배열

In [19]:
a1 = [1, 2, 3, 4, 5, 10, 20]
print(a1)
print(type(a1))
# print(a1.shape)

[1, 2, 3, 4, 5, 10, 20]
<class 'list'>


In [21]:
a2 = np.array([1, 2, 3, 4, 5, 10, 20, "가", "나", "a", "b", "c", "d"])
print(a2)
print(type(a2))
print(a2.shape) # 데이터의 크기 확인
print(a2.dtype) # 데이터 타입 확인

['1' '2' '3' '4' '5' '10' '20' '가' '나' 'a' 'b' 'c' 'd']
<class 'numpy.ndarray'>
(13,)
<U11


In [16]:
a3 = np.array([1, 2, 3, 4, 5, 10, 20, "30", "40"], float) # type= float(형태변환)
print(a3)
print(a3.dtype)

[ 1.  2.  3.  4.  5. 10. 20. 30. 40.]
float64


In [22]:
a4 = np.dtype('>i4')  # 4자리수를 바이트로 표현 
print(a4.name)

int32


In [23]:
# 벡터화 연산
data = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(data * 2) # 연산이 아닌 반복문
# print(data - 2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
# 배열로 바꾸기, 하나씩 벡터 연산 가능/ 반복문 지정 필요없음
data2 = np.array(data)
print(data2 * 2)
print(data2 + 2)
print(data2 - 2)

[ 0  2  4  6  8 10 12 14 16 18]
[ 2  3  4  5  6  7  8  9 10 11]
[-2 -1  0  1  2  3  4  5  6  7]


In [26]:
# 인덱스 접근
print(data2[0], data2[1])

0 1


### 2차원 배열

In [34]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.shape) #2행3열
print("____________________")
# 접근
print(arr[0])
print(arr[0][0])
print(len(arr))  # 행의 길이
print(len(arr[0])) # [0]번쩨 행의 열의 갯수


[[1 2 3]
 [4 5 6]]
(2, 3)
____________________
[1 2 3]
1
2
3


### 3차원 배열

In [43]:
arr = np.array([[[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]]])  # 처음이나 끝에 대괄호[]가 몇개인지 확인
print(arr)
print("-------------------")
print(arr[0])
print("-------------------")
print(arr[0][0])  # 데이터x, 주소만
print("-------------------")
print(arr[0][0][0])
print("-------------------")
print(arr.shape) # 2면 2행 4열
print(arr.ndim) # 몇차원인지 확인
print(len(arr), len(arr[0]), len(arr[0][0])) # 행 우선

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
-------------------
[[1 2 3 4]
 [5 6 7 8]]
-------------------
[1 2 3 4]
-------------------
1
-------------------
(2, 2, 4)
3
2 2 4


In [50]:
arr = np.array(1)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
#print(len(arr))  # 하나의 스칼라 즉, 길이는 없음
print("-----------------")
arr = np.array([[1]])  # 'tensor'라고 부름
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(len(arr))

1
int32
()
0
-----------------
[[1]]
int32
(1, 1)
2
1


### 배열의 인덱싱

- 배열에 저장되어 있는 데이터를 접근하는 방법

In [55]:
arr = np.array([0, 1, 2, 3, 4])
print(arr[2], arr[4], arr[-1], arr[-3])  # '-'는 역순

2 4 4 2


In [58]:
arr2 = np.array([[0, 1, 2], 
                 [3, 4, 5]])
print(arr2[0][2], arr2[0, 2], arr2[-1, -1]) #0행 2열/마지막행 마지막열

2 2 5


In [78]:
# fancy indexing 

arr3 = np.array([i for i in range(10)])
arr3
idx = np.array([True, False, True, False, True, False, True, False, True, False])

print(arr3[idx])
print(arr3 % 2)
print(arr3 % 2 == 0)
print(arr3[arr3 % 2 == 0])

# arr3에서 3의 배수를 찾아라
print(arr3[arr3 % 3 == 0])
# arr3에서 4로 나누면 1이 남는 수를 찾아라
print(arr3[arr3 % 4 == 1])
# arr3에서 3으로 나누면 나눠지고 4로 나누면 1이 남는 수를 찾아라 : 9
print(arr3[(arr3 % 3 == 0) & (arr3 % 4 == 1)])


[0 2 4 6 8]
[0 1 0 1 0 1 0 1 0 1]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[0 3 6 9]
[1 5 9]
[9]


### 배열의 슬라이싱

In [88]:
arr = np.array([[0, 1, 2, 3], 
                [4, 5, 6, 7], 
                [8, 9, 10, 11]])

print(arr[0, 0:2]) # 0행에서 0~2-1 까지 열
print("-------------")
print(arr[1:3, 0:2]) # 1행부터 3-1행까지
print("-------------")
print(arr[0, :]) # ':'=모든열 

# [[0, 1], [4,5]] 출력
print(arr[1, 0:2])
print(arr[-2, 0:2])
print(arr[1:2, :2])
print("-------------")
print(arr[[2, 1, 0], :]) #행의 위치를 선택적으로
print("-------------")
print(arr[ : , [1, 2]]) # 모든 행의 1, 2열만

[0 1]
-------------
[[4 5]
 [8 9]]
-------------
[0 1 2 3]
[4 5]
[4 5]
[[4 5]]
-------------
[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]
-------------
[[ 1  2]
 [ 5  6]
 [ 9 10]]


### numpy 자료형

+ b : 불리언
+ i : 정수      i8
+ u : 부호없는 정수
+ f : 부동소수점
+ c : 복소수
+ O : 객체 (대문자 오)
+ S : 바이트 문자열(대문자)     S24 
+ U : 유니코드 문자열(대문자)  2바이트씩

In [92]:
arr = np.array([1, 2, 3], dtype='f')  # 정수형-> 실수형
print(arr.dtype)
print(arr[0] + arr[1])

float32
3.0


In [95]:
arr = np.array([1, 2, 3], dtype='S') # 숫자가 아닌 문자(1 바이트)로 연결만
print(arr.dtype)
print(arr[0] + arr[1])
print("---------------------------")
arr = np.array([1, 2, 3], dtype='U') # 숫자가 아닌 문자(2 바이트)로 연결만
print(arr.dtype)
print(arr[0] + arr[1])

|S1
b'12'
---------------------------
<U1
12


In [105]:
# 데이터 타입 만들기
dt = np.dtype([('name', np.unicode_, 5), ("grades", np.float64, (2,))])

print(dt["name"])
print(dt["grades"])

print("------------------")

arr = np.array(["홍길동", "임꺽정", "신돌석", "김수한무 거북이와 두루미"], dtype=dt["name"])
print(arr)
print(arr.dtype)
                                                                
print("------------------")

arr = np.array([("홍길동", (5.0, 7.0)), ("임꺽정", (8.0, 9.0))], dtype=dt)
print(arr)                                                              

<U5
('<f8', (2,))
------------------
['홍길동' '임꺽정' '신돌석' '김수한무 ']
<U5
------------------
[('홍길동', [5., 7.]) ('임꺽정', [8., 9.])]


### 배열 생성 (return 값=배열)

In [114]:
arr = np.zeros(5) # 0이 5개의 배열
print(arr)
print(arr.dtype)  # 기본값=float
print(type(arr))

print("---------------")

arr = np.zeros(5, dtype="i")  #i는 int
print(arr)
print(arr.dtype) 
print(type(arr))

print("---------------")

arr = np.zeros(5, dtype="U")
print(arr)
print(arr.dtype)
print(type(arr))

print("---------------")
arr = np.zeros(5, dtype="U4") # 길이는 4글자까지
print(arr)
print(arr.dtype)
print(type(arr))

arr[0] = "abc"
arr[1] = "abcd"
arr[2] = "abcde"
print(arr)

print("---------------")

arr = np.zeros((2, 3))  #2행 3열짜리 배열
print(arr)

[0. 0. 0. 0. 0.]
float64
<class 'numpy.ndarray'>
---------------
[0 0 0 0 0]
int32
<class 'numpy.ndarray'>
---------------
['' '' '' '' '']
<U1
<class 'numpy.ndarray'>
---------------
['' '' '' '' '']
<U4
<class 'numpy.ndarray'>
['abc' 'abcd' 'abcd' '' '']
---------------
[[0. 0. 0.]
 [0. 0. 0.]]


In [126]:
## 리턴값은 무조건 배열
arr = np.ones((2, 3, 4))  #3행 4열짜리 배열이 2개 -> 3차원
print(arr)

print("---------------")

arr1 = np.zeros((2, 3))
arr2 = np.ones_like(arr1) # 기존의 값을 1로 바꿈
print(arr2)

print("---------------")

arr = np.empty((4, 3))  # 메모리의 기존값을 그대로 프린트
print(arr)

print("---------------")

arr = np.arange(10)  # 반복문 range와 같은 결과/ but, range의 결과값은 리스트
print(arr)

arr = np.linspace(0, 100, 5)  # 간격지정, 그래프 그릴때 자주 사용 / 0부터 100까지 5등분
print(arr)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
---------------
[[1. 1. 1.]
 [1. 1. 1.]]
---------------
[[1.03698325e-311 3.16202013e-322 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 1.25747884e-075]
 [3.60112761e+175 9.32711286e+164 2.73948854e-057]
 [4.51298350e-037 1.87936895e+160 3.15763701e-033]]
---------------
[0 1 2 3 4 5 6 7 8 9]
[  0.  25.  50.  75. 100.]


### 전치 연산(Transpose) 

In [127]:
# 2차원 이상
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr.T) #행과 열의 바꿈

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


### 배열의 크기 변형 : reshape(), flatten(), ravel()

In [130]:
# flatten(), ravel() -> 고차원의 배열을 1차원으로 변형
# reshape()은 행렬을 지정하면 다양하게 형태변형 가능

arr = np.arange(12)
print(arr)
print(arr.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)


In [134]:
arr1 = arr.reshape(3, 4)
print(arr1)
print(arr1.shape)

print("------------------------")

arr1 = arr.reshape(3, -1)  # -1 = 자동으로 열의 갯수 지정
print(arr1)
print(arr1.shape)

print("------------------------")

arr1 = arr.reshape(-1, 4)  # -1 = 자동으로 행의 갯수 지정
print(arr1)
print(arr1.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)


In [137]:
# 3차원으로 바꾸기

arr2 = arr.reshape(2, 2, 3) # 1차원 배열을 3차원으로 변경
print(arr2)

print("------------------------")

arr2 = arr.reshape(2, 2, -1) # 행의 갯수 자동 생성 
print(arr2)
print(arr2.shape)

print("------------------------")

arr2 = arr.reshape(2, -1, 3) # 열의 갯수 자동 생성
print(arr2)
print(arr2.shape)

print("------------------------")

arr2 = arr.reshape(-1, 2, 3)  # 면의 갯수 자동 생성
print(arr2)
print(arr2.shape)


[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
------------------------
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)


In [143]:
# 1차원으로 변경
print(arr.flatten())
print(arr.ravel())

print("---------------------------------------")

# 2차원 -> 1차원
print(arr2.flatten())
print(arr2.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
---------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [151]:
arr = np.arange(5)

print(arr.reshape(1, 5))
print(arr.reshape(5, 1))

print("---------------------------------------")

print(arr.reshape(1, 5).T)   # 전치행렬 사용 가능
print(arr.reshape(5, 1).T)

print("---------------------------------------")

print(arr[: , np.newaxis])  # 형식만 2차원으로 생성

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]]
---------------------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]
---------------------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]


### 배열 연결(병합) : stack, hstack, vstack, dstack, tile

In [157]:
# hstack, stack

arr1 = np.ones((2, 3))
print(arr1)
arr2 = np.ones((2, 2))
print(arr2)
# 행(수평)으로 합치기(행의 갯수만 같을 때)

print("---------------------------")

arr3 = np.hstack([arr1, arr2])
print(arr3)

print("---------------------------")

# 열로 합치기 (Error)
#arr4 = np.ㅍstack([arr1, arr2])
#print(arr4)



[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]]
---------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
---------------------------


AttributeError: module 'numpy' has no attribute 'ᄑstack'

In [160]:
# dstack / d=depth은 즉, 레벨. 차원의 수

# 3*4 배열의 갯수를 2배로 == 3 * 4 * 2
arr1 = np.ones((3, 4))
arr2 = np.zeros((3, 4))
# 2차 -> 3차

arr3 = np.dstack([arr1, arr2])
print(arr3)
print(arr3.shape) 

[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [165]:
# stack : dstack의 확장

arr1 = np.ones((3, 4))
arr2 = np.zeros((3, 4))

arr3 = np.stack([arr1, arr2])
print(arr3)
print(arr3.shape)

print("-----------------------")

arr4 = np.stack([arr1, arr2], axis=0)  # axis(cnr)=0 :기본값  # 2 * 3 * 4
print(arr4)
print(arr4.shape)

print("-----------------------")

arr4 = np.stack([arr1, arr2], axis=1)  # axis=1 :3 * 2 * 4
print(arr4)
print(arr4.shape)

print("-----------------------")

arr4 = np.stack([arr1, arr2], axis=2)  # axis=1 :3 * 4 * 2  == dstack()과 같은 결과
print(arr4)
print(arr4.shape)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
-----------------------
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
(2, 3, 4)
-----------------------
[[[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]

 [[1. 1. 1. 1.]
  [0. 0. 0. 0.]]]
(3, 2, 4)
-----------------------
[[[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]

 [[1. 0.]
  [1. 0.]
  [1. 0.]
  [1. 0.]]]
(3, 4, 2)


In [169]:
# tile

arr = np.array([[0, 1, 2], [3, 4, 5]])    # 2차원배열

print(np.tile(arr, 3))

print("-----------------------")

print(np.tile(arr, (3, 2)))

[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
-----------------------
[[0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]
 [0 1 2 0 1 2]
 [3 4 5 3 4 5]]


### 2차원 그리드 포인트 생성 : meshgrid()

In [170]:
x = np.arange(3)
x

array([0, 1, 2])

In [171]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [173]:
X, Y = np.meshgrid(x, y)

print(X)
print("--------------")
print(Y)


[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
--------------
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


In [179]:
# 반복문으로 돌려서 zip()으로 순서쌍으로 묶기 

z = [list(zip(x, y)) for x, y in zip(X, Y)]
z


[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [180]:
# 그래프 (기본그래프 = 막대 그래프)

import matplotlib.pylab as plt
plt.scatter(X, Y)  # 산포도

### 브로드 캐스팅(BroadCasting)

+ 크기가 서로 다른 행렬(벡터)끼리 연산을 가능하게 하는 것

In [ ]:
# 네트워크
# 브로드 케스팅 =  1 : 불특정 다수
# 멀티 캐스팅 = 1: 다
# 유니 캐스팅 = 1:1

In [195]:
print([i for i in range(5)[:]])
print([[i] for i in range(5)])
print([range(7)[i] for i in range(5)])
print([range(7)[i: i+3] for i in range(5)])

#print(np.vstack([range(7)[i: i+3] for i in range(5)]))

[0, 1, 2, 3, 4]
[[0], [1], [2], [3], [4]]
[0, 1, 2, 3, 4]
[range(0, 3), range(1, 4), range(2, 5), range(3, 6), range(4, 7)]


In [196]:
data = range(10)[0:3]  # range함수를 슬라이스[] 하는 방법

for i in data:
    print(i)
    
print("------------------------")

print(np.arange(5)[:, np.newaxis])

0
1
2
------------------------
[[0]
 [1]
 [2]
 [3]
 [4]]


In [200]:
x = np.vstack([range(7)[i:i+3] for i in range(5)])  # 5행 3열
y = np.arange(5)[:, np.newaxis]   # 1행 5열

print(x + y)

print("-----------------------")

y = np.arange(3)[:]
print(x + y)

[[ 0  1  2]
 [ 2  3  4]
 [ 4  5  6]
 [ 6  7  8]
 [ 8  9 10]]
-----------------------
[[0 2 4]
 [1 3 5]
 [2 4 6]
 [3 5 7]
 [4 6 8]]


### 차원 축소(dimension reduction) 연산

+ 최대값/최소값 : min, max, argmax, argmin
+ 대표값 : sum, mean, median, std, var
+ 불리언 : all(모두가 참일때 참), any(하나만 참이어도 참)
-----------------
행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 된다.
이러한 연산을 차원 축소 연산이라고 한다. 

In [5]:
x = np.array([1, 3, 2, -3])
result = np.argmin(x)  # 최소값의 위치
print(result)

print("--------------")

result = np.argmax(x)  # 최대값의 위치
print(result)

3
--------------
1


In [6]:
x = np.array([[1, 1], [2, 2]])

print(x.sum())
print("열 합계: ", x.sum(axis=0))
print("합 합계: ", x.sum(axis=1))


6
열 합계:  [3 3]
합 합계:  [2 4]


### 기술 통계 

+ len() : 길이
+ sum(), mean() : 합계, 평균
+ var(), std() : 분산, 표준편차
+ max(), min() : 최대값, 최소값
+ median() : 중앙값
+ percentile() : 사분위수  (주로 boxplot()으로 확인)

In [7]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

print("최소값 : ", np.percentile(x, 0))  # Shift+Tab
print("최대값 : ", np.percentile(x, 100))
print("1사분위 : ", np.percentile(x, 25))
print("2사분위 : ", np.percentile(x, 50))
print("3사분위 : ", np.percentile(x, 75))

최소값 :  -24.0
최대값 :  23.0
1사분위 :  0.0
2사분위 :  5.0
3사분위 :  10.0


In [8]:
# 여러개의 통계량을 한번에 확인하기

from scipy.stats import describe

describe(x)

# skewness : 왜도(정규 분포로 판단할때, 그래프가 왼쪽으로 기울어져 있음으면 음수, 오른쪽은 양?수로 판단하는 그래프의 기울기 정도, 좌우 비대칭)
# kurtosis : 첨도(그래프의 위아래 뽀죡한 정도 )


DescribeResult(nobs=26, minmax=(-24, 23), mean=4.8076923076923075, variance=119.84153846153846, skewness=-0.4762339485461929, kurtosis=0.37443381660038977)

### 정렬

In [14]:
arr = np.array([[4, 3, 5, 7], 
                [1, 12, 22, 9], 
                [2, 15, 1, 14]])

print(np.sort(arr))
print("---------------")
print(np.sort(arr, axis=1)) # 행으로 정렬
print("---------------")
print(np.sort(arr, axis=0)) # 열로 정렬
print("---------------")
print(arr)  # 정렬된 결과는 따로 저장

[[ 3  4  5  7]
 [ 1  9 12 22]
 [ 1  2 14 15]]
---------------
[[ 3  4  5  7]
 [ 1  9 12 22]
 [ 1  2 14 15]]
---------------
[[ 1  3  1  7]
 [ 2 12  5  9]
 [ 4 15 22 14]]
---------------
[[ 4  3  5  7]
 [ 1 12 22  9]
 [ 2 15  1 14]]


In [ ]:
# 원본에 정렬 적용
arr = np.sort(arr)

arr.sort()  # in-place


In [17]:
 # argsort 
arr1 = np.array([42, 38, 12, 25])  # 정렬 시켰을때 값의 인덱스 표시 
idx = np.argsort(arr1)
print(arr1[idx])

[12 25 38 42]


In [23]:
# 내림차순

print(np.sort(arr1)[::-1])  # [시작위치:끝위치:간격]

# 또는
print(arr1[np.argsort(-arr1)])

[42 38 25 12]
[42 38 25 12]


In [22]:
# 슬라이스 : arr[시작위치 끝위치:간격]
ex = range(10)
print(list(ex[::2]))
print(list(ex[1::2]))
print(list(ex[::-1]))
print(list(ex[::-2]))

[0, 2, 4, 6, 8]
[1, 3, 5, 7, 9]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
[9, 7, 5, 3, 1]


### 난수

+ rand() : 0 ~ 1 사이의 균일분포
+ randn() : 가우시안 표준 정규분포(평균 : 0, 표준편차 : 1)
+ randint() : 균일분포의 정수 난수 

In [27]:
print(np.random.rand(10))  # 배열로 리런
print("-----------------------")
print(np.random.rand(3, 5))  # 2차원으로 리턴

[0.74803112 0.1501348  0.00745467 0.88169084 0.15848341 0.08317822
 0.63792066 0.68907938 0.4209862  0.57178625]
-----------------------
[[0.80508465 0.23850353 0.4036845  0.92391334 0.77656122]
 [0.01662616 0.87717697 0.57197214 0.28460685 0.18701131]
 [0.5008674  0.83481766 0.16926237 0.25344321 0.71456957]]


In [41]:
print(np.random.randint(10))   # 0 ~ 9 사이의 난수 1개
print("-----------------------")
print(np.random.randint(11, 20))  # 범위 지정 
print("-----------------------")
print(np.random.randint(11, 20, size=100))  # 갯수 지정 
print("-----------------------")
print(np.random.randint(11, 20, size=(3, 4)))  # 튜플로 지정

6
-----------------------
16
-----------------------
[14 14 12 11 15 11 16 16 14 15 14 11 13 17 15 15 19 11 12 12 12 14 13 13
 11 16 13 11 16 18 14 15 12 11 11 14 17 12 11 12 12 17 14 17 16 19 12 11
 16 18 14 13 16 18 11 13 16 15 19 11 13 12 19 13 12 18 12 11 14 14 15 12
 17 18 15 17 19 19 19 18 13 15 16 18 18 12 17 12 11 16 15 14 11 12 11 14
 13 12 17 18]
-----------------------
[[15 14 13 19]
 [13 12 14 12]
 [17 12 19 13]]


In [47]:
# 재현성(난수 고정)

np.random.seed(10)
np.random.rand(2)

array([0.77132064, 0.02075195])

In [52]:
# 데이터의 순서 바꾸기

x = np.arange(10)
print(x)

np.random.shuffle(x)
print(x)

[0 1 2 3 4 5 6 7 8 9]
[7 5 9 4 0 1 2 3 8 6]


In [67]:
# 샘플링 : 복원(default), 비복원 : replace= T(default) or F

print(np.random.choice(5, 5))   # 0~4까지의 숫자 중 5번 추출(복원)
print(np.random.choice(5, 3)) 
print("-----------------------------")
print(np.random.choice(5, 5, replace=False))  # 비복원
print("-----------------------------")
print(np.random.choice(5, 10, p=[0.1, 0, 0.3, 0.6, 0]))   # 5개 중 10번, p=probability[확률로 난수 조정]

[0 2 0 1 4]
[3 4 0]
-----------------------------
[4 3 1 2 0]
-----------------------------
[3 0 3 3 3 2 2 3 2 3]


### 정수형 데이터 카운팅 : unique, bincount

In [71]:
arr = np.array(['a', 'b', 'b', 'c', 'a'])

print(len(arr))
print(np.unique(arr))

print("---------------")
idx, cnt = np.unique(arr, return_counts=True)  # 리턴값은 튜플
print(idx)
print(cnt) # 카테고리 별로 갯수 구분 / R에서는 table()

5
['a' 'b' 'c']
---------------
['a' 'b' 'c']
[2 2 1]


In [73]:
# bincount : 발생하지 않은 사건에 대해서도 카운팅/ 비어있는 값을 카운팅

arr = np.array([1, 1, 2, 2, 2, 3])
print(np.bincount(arr, minlength=6))  # 0~5 사이 값 중 한번도 나오지 않은 값을 표시

[0 2 3 1 0 0]


### 실습

+ data : https://grouplens.org/datasets/movielens/
         Older Dataset에서 MovieLens 1M DataSet 받기: ml-1m.zip(size: 6 MB, checksum)

In [2]:
# 데이터 불러오기 
data = np.loadtxt("data/ml-1m/ratings.dat", delimiter="::", dtype=np.int64)

In [3]:
print(data)

[[        1      1193         5 978300760]
 [        1       661         3 978302109]
 [        1       914         3 978301968]
 ...
 [     6040       562         5 956704746]
 [     6040      1096         4 956715648]
 [     6040      1097         4 956715569]]


In [3]:
# 1행부터 20행까지 출력
data[:21, :]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368],
       [        1,       595,         5, 978824268],
       [        1,       938,         4, 978301752],
       [        1,      2398,         4, 978302281],
       [        1,      2918,         4, 978302124],
       [        1,      1035,         5, 978301753],
       [        1,      2791,         4, 978302188],
       [        1,      2687,         3, 978824268],
       [        1,      2018,         4, 978301777],
       [        1,      3105,         5, 97830

In [4]:
# 21행부터 30행까지 userid와 movieid만 출력
data[21:31, 0:2]

array([[   1,  720],
       [   1, 1270],
       [   1,  527],
       [   1, 2340],
       [   1,   48],
       [   1, 1097],
       [   1, 1721],
       [   1, 1545],
       [   1,  745],
       [   1, 2294]], dtype=int64)

In [5]:
# 전체 평점 평균 = 열 평균
print(data[:, 2].mean())
print(np.mean(data[:, 2]))

3.581564453029317
3.581564453029317


In [6]:
# 사용자별로 평점 평균  (10명만 출력)
user_id = np.unique(data[:, 0])
print(user_id.shape)

mean_values = []
for id in user_id:
    data_for_user = data[data[:, 0] == id, :] # 행은 0번째,열은 전체
    value = data_for_user[:, 2].mean() # 영화 평론만(2) 평균
    mean_values.append([id, value])
    
print("결과 : ", mean_values[:10])

(6040,)
결과 :  [[1, 4.188679245283019], [2, 3.7131782945736433], [3, 3.9019607843137254], [4, 4.190476190476191], [5, 3.1464646464646466], [6, 3.9014084507042255], [7, 4.32258064516129], [8, 3.884892086330935], [9, 3.7358490566037736], [10, 4.114713216957606]]


In [11]:
# 최고 평점 구하기(누가 얼마를)
# UserID::MovieID::Rating::Timestamp

arr_mean_values = np.array(mean_values)  # 데이터 타입을 np.array로 바꾸기

#print(np.argsort(arr_mean_values[:, 1]))  # 평점
print(np.argsort(arr_mean_values[:, 1])[::-1])  # 내침차순 정렬 [::-1]
#print(arr_mean_values[282])  # 282번째에 있는 가장 높은 평점

#print(arr_mean_values[np.argsort(arr_mean_values[:, 1])[::-1]][0]) # 한줄

#print("----------------------------------------")

# 최대값만 구한다면
# print(np.max(arr_mean_values[:, 1])) 정말로 최대값만 구해짐..ㅠㅠ
# 또는 argmax()를 사용
#print(np.argmax(arr_mean_values[:, 1]))
#print(arr_mean_values[282])

print(arr_mean_values[np.argmax(arr_mean_values[:, 1])])


[ 282 2338 3323 ... 2743 4485 3597]
[283.           4.96296296]


In [12]:
# 결과값을 파일로 저장
# 기본함수 open() 사용가능

np.savetxt("data/ml-1m/id_rations.csv", arr_mean_values, delimiter=",", fmt="%.1f") # fmt(format)= 소수점 1자리까지 저장