In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import sys

#### 단일 cell을 통한 계산 처리 과정 : 기본 사용법

In [151]:
# 입력 데이터 준비
inputs = np.array([[[1, 2]]])

In [152]:
tf.reset_default_graph()
tf.set_random_seed(777)
tf_inputs = tf.constant(inputs, dtype=tf.float32)

In [153]:
import warnings
warnings.filterwarnings(action="ignore")

tf.reset_default_graph()
tf.set_random_seed(777)
tf_inputs = tf.constant(inputs, dtype=tf.float32)

# 1 * 3의 matrix 출력([6, 7, 8]과 같은)
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=3)
# 동작 함수(셀 실행)
outputs, state = tf.nn.dynamic_rnn(cell=rnn_cell, dtype=tf.float32, inputs=tf_inputs)

print(outputs)
print(state)

print("\n\n Weights")
for w in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
    print(w)

Tensor("rnn/transpose_1:0", shape=(1, 1, 3), dtype=float32)
Tensor("rnn/while/Exit_3:0", shape=(1, 3), dtype=float32)


 Weights
<tf.Variable 'rnn/basic_rnn_cell/kernel:0' shape=(5, 3) dtype=float32_ref>
<tf.Variable 'rnn/basic_rnn_cell/bias:0' shape=(3,) dtype=float32_ref>


In [154]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_run, state_run = sess.run([outputs, state])
    
    print("Output Value")
    print(output_run)
    
    print("State Value")
    print(state_run)
    
    variables_names = [v.name for v in tf.trainable_variables()]
    print(variables_names)
    values = sess.run(variables_names)
    for k, v in zip(variables_names, values):
        print(k, v)

Output Value
[[[-0.9314169   0.75578666 -0.6819246 ]]]
State Value
[[-0.9314169   0.75578666 -0.6819246 ]]
['rnn/basic_rnn_cell/kernel:0', 'rnn/basic_rnn_cell/bias:0']
rnn/basic_rnn_cell/kernel:0 [[-0.62831575  0.38538355  0.79733914]
 [-0.5203329   0.30046564 -0.8150209 ]
 [ 0.39399797  0.16670114  0.4062907 ]
 [-0.6391754   0.8460203   0.5266966 ]
 [ 0.41124135  0.66347724 -0.0210759 ]]
rnn/basic_rnn_cell/bias:0 [0. 0. 0.]


#### 다중 cell

In [158]:
# I work at google = [[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]] / one-hot incording
# I google at work = [[1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0,]]

inputs = np.array([[[1,0,0,0], [0,1,0,0], [0,0,1,0], [0,0,0,1]],
                   [1,0,0,0], [0,0,0,1], [0,0,1,0], [0,1,0,0,]])

In [164]:
tf.reset_default_graph()
tf.set_random_seed(777)
tf_inputs = tf.constant(inputs, dtype=tf.float32)

rnn_cell = tf.contrib.rnn.BasicRNNCell(num_units=3)
outputs, state = tf.nn.dynamic_rnn(cell=rnn_cell, dtype=tf.float32, inputs=tf_inputs)
variables_names = [v.name for v in tf.trainable_variables()]

print(outputs)
print("----------------------")
print(state)
print("----------------------")
for w in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
    print(w)  

ValueError: setting an array element with a sequence.

In [157]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_run, state_run = sess.run([outputs, state])
    
    print("Output Value")
    print(output_run)
    
    print("State Value")
    print(state_run)
    
    values = sess.run(variables_names)
    for k, v in zip(variables_names, values):
        print(k, v)

ValueError: Fetch argument <tf.Tensor 'rnn/transpose_1:0' shape=(1, 1, 3) dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("rnn/transpose_1:0", shape=(1, 1, 3), dtype=float32) is not an element of this graph.)

In [48]:
tf.reset_default_graph()
h = [1, 0, 0, 0]
e = [0, 1, 0, 0]
l = [0, 0, 1, 0]
o = [0, 0, 0, 1]

rnn_cell = tf.contrib.rnn.BasicRNNCell(num_units=3)

x_data = np.array([[h, e, l, l, o]], dtype=np.float32)
outputs, state = tf.nn.dynamic_rnn(cell=rnn_cell, dtype=tf.float32, inputs=x_data)
variables_names = [v.name for v in tf.trainable_variables()]

print(outputs)
print("----------------------")
print(state)
print("----------------------")
for w in tf.get_collection(tf.GraphKeys.TRAINABLE_VARIABLES):
    print(w)

Tensor("rnn/transpose_1:0", shape=(1, 5, 3), dtype=float32)
----------------------
Tensor("rnn/while/Exit_3:0", shape=(1, 3), dtype=float32)
----------------------
<tf.Variable 'rnn/basic_rnn_cell/kernel:0' shape=(7, 3) dtype=float32_ref>
<tf.Variable 'rnn/basic_rnn_cell/bias:0' shape=(3,) dtype=float32_ref>


In [49]:
# 결과
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    output_run, state_run = sess.run([outputs, state])
    
    print("Output Value")
    print(output_run)
    
    print("State Value")
    print(state_run)
    
    values = sess.run(variables_names)
    for k, v in zip(variables_names, values):
        print(k, v)

Output Value
[[[-0.00233542  0.05193848 -0.5742626 ]
  [-0.3266077   0.10008996  0.13926423]
  [-0.15353745 -0.30581573 -0.60393846]
  [ 0.45869008 -0.7267591  -0.725342  ]
  [ 0.86987185 -0.8058975  -0.08595657]]]
State Value
[[ 0.86987185 -0.8058975  -0.08595657]]
rnn/basic_rnn_cell/kernel:0 [[-0.00233543  0.05198526 -0.6538598 ]
 [-0.6641659   0.4281752   0.37294662]
 [ 0.05170107 -0.5519403  -0.6884491 ]
 [ 0.49469054 -0.33068338  0.04296321]
 [ 0.2556615  -0.3970473   0.16777241]
 [-0.39017454  0.23633456 -0.11033732]
 [-0.60251516  0.59371984  0.39467812]]
rnn/basic_rnn_cell/bias:0 [0. 0. 0.]


#### hihello 학습 과정

In [165]:
idx2char = ['h', 'i', 'e', 'l', 'o']
x_one_hot = [[[1, 0, 0, 0, 0], 
              [0, 1, 0, 0, 0], 
              [1, 0, 0, 0, 0],
              [0, 0, 1, 0, 0], 
              [0, 0, 0, 1, 0], 
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 1]]]  
#             [0, 0, 0, 0, 1] 삭제__sequence len = 6일때

# x_data = [[0, 1, 0, 2, 3, 3]] # hihell
y_data = [[0, 1, 0, 2, 3, 3, 4]] # ihello  # 0 삭제_shape 맞추기

In [166]:
# parameter
sequence_len = 7  # 입력 데이터 갯수
num_classes = 5  # 입력 데이터의 종류(중복제외)
batch_size = 1  

In [167]:
tf.reset_default_graph()

# X, y 준비
X = tf.placeholder(tf.float32, shape=[None, sequence_len, num_classes])  # shape=[전체갯수, 입력갯수, 원하는 출력갯수]
y = tf.placeholder(tf.int32, shape=[None, sequence_len])  # 정답

In [168]:
# rnn 모델
cell = tf.contrib.rnn.BasicRNNCell(num_units=num_classes)
outputs, state = tf.nn.dynamic_rnn(cell=cell, inputs=X, dtype=tf.float32)
print(outputs)
print(state)

Tensor("rnn/transpose_1:0", shape=(?, 7, 5), dtype=float32)
Tensor("rnn/while/Exit_3:0", shape=(?, 5), dtype=float32)


In [169]:
# 평면화(Flat Layer) __tf.flat()
X_for_fc = tf.reshape(outputs, [-1, num_classes])
print(X_for_fc)

Tensor("Reshape:0", shape=(?, 5), dtype=float32)


In [170]:
#Fully Connected (W, b, logit)
outputs = tf.contrib.layers.fully_connected(inputs=X_for_fc, num_outputs=num_classes, activation_fn=None)

outputs = tf.reshape(outputs, [batch_size, sequence_len, num_classes]) 
W = tf.ones([batch_size, sequence_len])
cost = tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=y, weights=W)
train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(10):
        _, c = sess.run([train, cost], feed_dict={X:x_one_hot, y:y_data})
        result = sess.run(tf.argmax(outputs, 2), feed_dict={X:x_one_hot})
        print(i, "cost", c, "    prediction:", result, "    정답:", y_data)
        
    result_str = [idx2char[c] for c in np.squeeze(result)]  #np.squeeze():()축 하나 제외
    print("결과 : ", ",".join(result_str))

0 cost 1.5060341     prediction: [[0 0 0 0 3 3 3]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
1 cost 1.2012122     prediction: [[0 0 0 0 3 3 3]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
2 cost 0.9637184     prediction: [[0 1 0 2 3 3 3]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
3 cost 0.742112     prediction: [[0 1 0 2 3 3 3]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
4 cost 0.54294395     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
5 cost 0.3977509     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
6 cost 0.29055333     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
7 cost 0.2077953     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
8 cost 0.1498015     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
9 cost 0.10862583     prediction: [[0 1 0 2 3 3 4]]     정답: [[0, 1, 0, 2, 3, 3, 4]]
결과 :  h,i,h,e,l,l,o


#### 두 번째 예제

In [171]:
# 입력 데이터 준비
# sample = " You will have to submit to your fate whether you will or not."
sample = " if you want you"
idx2char = list(set(sample))
print(idx2char)

char2idx = {c: i for i, c in enumerate(idx2char)}
print(char2idx)

sample_idx = [char2idx[c] for c in sample]
print(sample_idx)

x_data = [sample_idx[:-1]]
y_data = [sample_idx[1:]]

[' ', 'i', 'n', 'w', 'o', 'f', 't', 'y', 'a', 'u']
{' ': 0, 'i': 1, 'n': 2, 'w': 3, 'o': 4, 'f': 5, 't': 6, 'y': 7, 'a': 8, 'u': 9}
[0, 1, 5, 0, 7, 4, 9, 0, 3, 8, 2, 6, 0, 7, 4, 9]


In [172]:
# parameter
num_classes = len(char2idx)
batch_size = 1
sequence_len = len(sample) -1

In [173]:
tf.reset_default_graph()

# X, y 준비
X = tf.placeholder(tf.int32, shape=[None, sequence_len, num_classes])
y = tf.placeholder(tf.int32, shape=[None, sequence_len])  

x_one_hot = tf.one_hot(X, num_classes)

In [174]:
cell = tf.contrib.rnn.BasicRNNCell(num_units=num_classes)
outputs, state = tf.nn.dynamic_rnn(cell=cell, inputs=x_one_hot, dtype=tf.float32)

W = tf.ones([batch_size, sequence_len])
cost = tf.reduce_mean(tf.contrib.seq2seq.sequence_loss(logits=outputs, targets=y, weights=W))
train = tf.train.AdamOptimizer(learning_rate=0.1).minimize(cost)

ValueError: Input 0 of layer basic_rnn_cell_1 is incompatible with the layer: expected ndim=2, found ndim=3. Full shape received: [None, 10, 10]

In [133]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for i in range(100):
        _, c = sess.run([train, cost], feed_dict={X:x_data, y:y_data})
        result = sess.run(tf.argmax(outputs, 2), feed_dict={X:x_data})
        print(i, "cost", c, "    prediction:", result, "    정답:", y_data)
        
        result_str = [idx2char[c] for c in np.squeeze(result)] 
        print("결과 : ", ",".join(result_str))

ValueError: Cannot feed value of shape (1, 6) for Tensor 'Placeholder:0', which has shape '(?, 15, 10)'

## LSTM(Long Short Term Memory)

+ BackPropagation Through Time(BPTT)
    - Gradient Vanishing problem(기울기 소실) : 값이 작아져 문제
    - Gradient Exploding problem(기울기 폭주) : 값이 너무 커져서 문제 ex.자연어처리시 문장 혹은 단어가 길어질때 발생

In [5]:
tf.reset_default_graph()
tf.set_random_seed(777)

inputs = np.array([[[1, 0]]])

tf_inputs = tf.constant(inputs, dtype=tf.float32)
cell = tf.nn.rnn_cell.LSTMCell(num_units=1)
outputs, states = tf.nn.dynamic_rnn(cell=cell, dtype=tf.float32, inputs=tf_inputs)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    outputs_run, states_run = sess.run([outputs, states])
    
    print(outputs_run) # y값
    print(states_run.h) # hidden state(s)
    print(states_run.c) # memory cell(추가)

[[[0.09927537]]]
[[0.09927537]]
[[0.18134572]]


### Dynamic RNN

#### 데이터 준비

In [11]:
paragraph_dict_list = [
         {'paragraph': 'dishplace is located in sunnyvale downtown there is parking around the area but it can be difficult to find during peak business hours my sisters and i came to this place for dinner on a weekday they were really busy so i highly recommended making reservations unless you have the patience to wait', 'category': 'food'},
         {'paragraph': 'service can be slower during busy hours but our waiter was courteous and help gave some great entree recommendations', 'category': 'food'},
         {'paragraph': 'portions are huge both french toast and their various omelettes are really good their french toast is probably 1.5x more than other brunch places great place to visit if you are hungry and dont want to wait 1 hour for a table', 'category': 'food'},
         {'paragraph': 'we started with apps going the chicken and waffle slides and chicken nachos the sliders were amazing and the nachos were good too maybe by themselves the nachos would have scored better but after those sliders they were up against some tough competition', 'category': 'food'},
         {'paragraph': 'the biscuits and gravy was too salty two people in my group had the gravy and all thought it was too salty my hubby ordered a side of double egg and it was served on two small plates who serves eggs to one person on separate plates we commented on that when it was delivered and even the server laughed and said she doesnt know why the kitchen does that presentation of food is important and they really missed on this one', 'category': 'food'},
         {'paragraph': 'the garlic fries were a great starter (and a happy hour special) the pancakes looked and tasted great and were a fairly generous portion', 'category': 'food'},
         {'paragraph': 'our meal was excellent i had the pasta ai formaggi which was so rich i didnt dare eat it all although i certainly wanted to excellent flavors with a great texture contrast between the soft pasta and the crisp bread crumbs too much sauce for me but a wonderful dish', 'category': 'food'},
         {'paragraph': 'what i enjoy most about palo alto is so many restaurants have dog-friendly seating outside i had bookmarked italico from when they first opened about a 1.5 years ago and was jonesing for some pasta so time to finally knock that bookmark off', 'category': 'food'},
         {'paragraph': 'the drinks came out fairly quickly a good two to three minutes after the orders were taken i expected my iced tea to taste a bit more sweet but this was straight up green tea with ice in it not to complain of course but i was pleasantly surprised', 'category': 'food'},
         {'paragraph': 'despite the not so good burger the service was so slow the restaurant wasnt even half full and they took very long from the moment we got seated to the time we left it was almost 2 hours we thought that it would be quick since we ordered as soon as we sat down my coworkers did seem to enjoy their beef burgers for those who eat beef however i will not be returning it is too expensive and extremely slow service', 'category': 'food'},
    
         {'paragraph': 'the four reigning major champions simona halep caroline wozniacki angelique kerber and defending us open champion sloane stephens could make a case for being the quartet most likely to succeed especially as all but stephens has also enjoyed the no1 ranking within the last 14 months as they prepare for their gruelling new york campaigns they currently hold the top four places in the ranks', 'category': 'sports'},
         {'paragraph': 'the briton was seeded nn7 here last year before a slump in form and confidence took her down to no46 after five first-round losses but there have been signs of a turnaround including a victory over a sub-par serena williams in san jose plus wins against jelena ostapenko and victoria azarenka in montreal. konta pulled out of new haven this week with illness but will hope for good things where she first scored wins in a major before her big breakthroughs to the semis in australia and wimbledon', 'category': 'sports'},
         {'paragraph': 'stephens surged her way back from injury in stunning style to win her first major here last year—and ranked just no83 she has since proved what a big time player she is winning the miami title via four fellow major champions then reaching the final at the french open back on north american hard courts she ran to the final in montreal only just edged out by halep she has also avoided many of the big names in her quarter—except for wild card azarenka as a possible in the third round', 'category': 'sports'},
         {'paragraph': 'when it came to england chances in the world cup it would be fair to say that most fans had never been more pessimistic than they were this year after enduring years of truly dismal performances at major tournaments – culminating in the 2014 event where they failed to win any of their three group games and finished in bottom spot those results led to the resignation of manager roy hodgson', 'category': 'sports'},
         {'paragraph': 'the team that eliminated russia – croatia – also improved enormously during the tournament before it began their odds were 33/1 but they played with real flair and star players like luka modric ivan rakitic and ivan perisic showed their quality on the world stage having displayed their potential by winning all three of their group stage games croatia went on to face difficult tests like the semi-final against england', 'category': 'sports'},
         {'paragraph': 'the perseyside outfit finished in fourth place in the premier league table and without a trophy last term after having reached the champions league final before losing to real madrid', 'category': 'sports'},
         {'paragraph': 'liverpool fc will return to premier league action on saturday lunchtime when they travel to leicester city in the top flight as they look to make it four wins in a row in the league', 'category': 'sports'},
         {'paragraph': 'alisson signed for liverpool fc from as roma this summer and the brazilian goalkeeper has helped the reds to keep three clean sheets in their first three premier league games', 'category': 'sports'},
         {'paragraph': 'but the rankings during that run-in to new york hid some very different undercurrents for murray had struggled with a hip injury since the clay swing and had not played a match since losing his quarter-final at wimbledon and he would pull out of the us open just two days before the tournament began—too late however to promote nederer to the no2 seeding', 'category': 'sports'},
         {'paragraph': 'then came the oh-so-familiar djokovic-nadal no-quarter-given battle for dominance in the thiadal more than once pulled off a reverse smash and had his chance to seal the tie-break but it was djokovic serving at 10-9 who dragged one decisive error from nadal for a two-sets lead', 'category': 'sports'}
]

df = pd.DataFrame(paragraph_dict_list)
df = df[["paragraph", "category"]]
df

paragraph category
0   dishplace is located in sunnyvale downtown the...     food
1   service can be slower during busy hours but ou...     food
2   portions are huge both french toast and their ...     food
3   we started with apps going the chicken and waf...     food
4   the biscuits and gravy was too salty two peopl...     food
5   the garlic fries were a great starter (and a h...     food
6   our meal was excellent i had the pasta ai form...     food
7   what i enjoy most about palo alto is so many r...     food
8   the drinks came out fairly quickly a good two ...     food
9   despite the not so good burger the service was...     food
10  the four reigning major champions simona halep...   sports
11  the briton was seeded nn7 here last year befor...   sports
12  stephens surged her way back from injury in st...   sports
13  when it came to england chances in the world c...   sports
14  the team that eliminated russia – croatia – al...   sports
15  the perseyside outfit finished in fourth place...   sports
16  liverpool fc will return to premier league act...   sports
17  alisson signed for liverpool fc from as roma t...   sports
18  but the rankings during that run-in to new yor...   sports
19  then came the oh-so-familiar djokovic-nadal no...   sports

#### Preprocessing

In [12]:
results = set() # 순서없이, 중복된 데이터없이
df["paragraph"].str.lower().str.split().apply(results.update)

0     None
1     None
2     None
3     None
4     None
5     None
6     None
7     None
8     None
9     None
10    None
11    None
12    None
13    None
14    None
15    None
16    None
17    None
18    None
19    None
Name: paragraph, dtype: object

In [13]:
results

{'(and',
 '1',
 '1.5',
 '1.5x',
 '10-9',
 '14',
 '2',
 '2014',
 '33/1',
 'a',
 'about',
 'action',
 'after',
 'against',
 'ago',
 'ai',
 'alisson',
 'all',
 'almost',
 'also',
 'although',
 'alto',
 'amazing',
 'american',
 'and',
 'angelique',
 'any',
 'apps',
 'are',
 'area',
 'around',
 'as',
 'at',
 'australia',
 'avoided',
 'azarenka',
 'back',
 'battle',
 'be',
 'beef',
 'been',
 'before',
 'began',
 'began—too',
 'being',
 'better',
 'between',
 'big',
 'biscuits',
 'bit',
 'bookmark',
 'bookmarked',
 'both',
 'bottom',
 'brazilian',
 'bread',
 'breakthroughs',
 'briton',
 'brunch',
 'burger',
 'burgers',
 'business',
 'busy',
 'but',
 'by',
 'came',
 'campaigns',
 'can',
 'card',
 'caroline',
 'case',
 'certainly',
 'champion',
 'champions',
 'chance',
 'chances',
 'chicken',
 'city',
 'clay',
 'clean',
 'commented',
 'competition',
 'complain',
 'confidence',
 'contrast',
 'could',
 'course',
 'courteous',
 'courts',
 'coworkers',
 'crisp',
 'croatia',
 'crumbs',
 'culminating

In [19]:
# 일련번호 부여
idx2word = dict(enumerate(results))
print(idx2word[396])
print(idx2word[100])

courts
different


In [22]:
# 문자 -> 숫자 변환
word2idx = {v:k for k, v in idx2word.items()}
word2idx["down"]
word2idx["courts"]

396

In [48]:
# paragraph 전처리
def encoded_paragraph(para):
    words = para.split()
    encoded = []
    for w in words:
        encoded.append([word2idx[w]])
        
    return encoded

# category 숫자로 변경
def encoded_category(cate):
    if cate == "food":
        return [1, 0]
    else:
        return [0, 1]
    
# 함수 추가
def word_cnt(para):
    return len(para.split())

In [49]:
df["enc_paragraph"] = df.paragraph.apply(encoded_paragraph)
df.head()

paragraph category  \
0  dishplace is located in sunnyvale downtown the...     food   
1  service can be slower during busy hours but ou...     food   
2  portions are huge both french toast and their ...     food   
3  we started with apps going the chicken and waf...     food   
4  the biscuits and gravy was too salty two peopl...     food   

                                       enc_paragraph enc_category  seq_lenght  
0  [[349], [37], [463], [283], [212], [452], [172...       [1, 0]          53  
1  [[372], [104], [118], [39], [223], [483], [231...       [1, 0]          19  
2  [[225], [355], [208], [205], [76], [507], [354...       [1, 0]          42  
3  [[131], [360], [193], [41], [408], [292], [324...       [1, 0]          43  
4  [[292], [107], [354], [106], [246], [410], [35...       [1, 0]          82

In [50]:
df["enc_category"] = df.category.apply(encoded_category)
df.head()

paragraph category  \
0  dishplace is located in sunnyvale downtown the...     food   
1  service can be slower during busy hours but ou...     food   
2  portions are huge both french toast and their ...     food   
3  we started with apps going the chicken and waf...     food   
4  the biscuits and gravy was too salty two peopl...     food   

                                       enc_paragraph enc_category  seq_lenght  
0  [[349], [37], [463], [283], [212], [452], [172...       [1, 0]          53  
1  [[372], [104], [118], [39], [223], [483], [231...       [1, 0]          19  
2  [[225], [355], [208], [205], [76], [507], [354...       [1, 0]          42  
3  [[131], [360], [193], [41], [408], [292], [324...       [1, 0]          43  
4  [[292], [107], [354], [106], [246], [410], [35...       [1, 0]          82

In [52]:
df["seq_length"] = df.paragraph.apply(word_cnt)
df.head()

paragraph category  \
0  dishplace is located in sunnyvale downtown the...     food   
1  service can be slower during busy hours but ou...     food   
2  portions are huge both french toast and their ...     food   
3  we started with apps going the chicken and waf...     food   
4  the biscuits and gravy was too salty two peopl...     food   

                                       enc_paragraph enc_category  seq_lenght  \
0  [[349], [37], [463], [283], [212], [452], [172...       [1, 0]          53   
1  [[372], [104], [118], [39], [223], [483], [231...       [1, 0]          19   
2  [[225], [355], [208], [205], [76], [507], [354...       [1, 0]          42   
3  [[131], [360], [193], [41], [408], [292], [324...       [1, 0]          43   
4  [[292], [107], [354], [106], [246], [410], [35...       [1, 0]          82   

   seq_length  
0          53  
1          19  
2          42  
3          43  
4          82

In [53]:
# 문장의 최대 길이 알아내기
max_word_cnt = 0

for row in df["paragraph"]:
    if len(row.split()) > max_word_cnt:
        max_word_cnt = len(row.split())
    
print(max_word_cnt)

91


In [54]:
# 문장의 길이가 91개가 안될 경우 -1로 채워준다.
def sequence_padding(enc_para):
    seq_len = len(enc_para)
    for i in range(seq_len, max_word_cnt):
        enc_para.append([-1])
        
    return enc_para
    

In [56]:
df["enc_paragraph"] = df.enc_paragraph.apply(sequence_padding)

In [57]:
print(df["enc_paragraph"][0])

[[349], [37], [463], [283], [212], [452], [172], [37], [391], [7], [292], [62], [82], [250], [104], [118], [34], [501], [527], [223], [26], [247], [231], [162], [475], [354], [368], [70], [501], [338], [456], [486], [257], [464], [310], [239], [313], [198], [128], [483], [440], [368], [470], [529], [457], [392], [113], [319], [524], [292], [156], [501], [499], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1]]


In [58]:
# 입력값들을 배열(tensor)로 변환
enc_paragraph = np.array(df.enc_paragraph.tolist())
enc_category = np.array(df.enc_category.tolist())
seq_length = np.array(df.seq_length.tolist())

#### 모델 구축

In [59]:
train_X = enc_paragraph
train_y = enc_category

print(train_X.shape, train_y.shape)

(20, 91, 1) (20, 2)


In [72]:
tf.reset_default_graph()
tf.set_random_seed(777)

# parameter
lr = 0.001
n_epochs = 300

X = tf.placeholder(tf.float32, shape=[None, max_word_cnt,1])  #shape=[전체데이터, 91, 출력갯수]
y = tf.placeholder(tf.int32, shape=[None, 2]) # food, sport 둘 중 하나==2

#레이어 추가
embeded = tf.layers.dense(X, 5)

cell = tf.nn.rnn_cell.LSTMCell(num_units=64)
output, state = tf.nn.dynamic_rnn(cell=cell, inputs=embeded, dtype=tf.float32, sequence_length=seq_length)
#print(output)
#print(state)

# 코드 압축(dense()==레이어 생성)
first_layer = tf.layers.dense(state.h, 32) # 최종결과값(은닉층) 적용
logit = tf.layers.dense(first_layer, 2)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits_v2(logits=logit, labels=y))
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

#print(X)
#print(embeded)
#print(state)
#print(first_layer)
#print(logit)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(n_epochs):
        _, c = sess.run([train, cost], feed_dict={X:train_X, y:train_y})
        
        if epoch % 50 == 0:
            pred = tf.nn.softmax(logit)
            correct_pred = tf.equal(tf.argmax(pred, 1), tf.argmax(y, 1))
            accuracy = tf.reduce_mean(tf.cast(correct_pred, "float"))
            cur_acc = accuracy.eval({X:train_X, y:train_y})
            print("epoch:" + str(epoch) + ", cost:" + str(c) + ", acc:" + str(cur_acc))

epoch:0, cost:0.8654138, acc:0.5
epoch:50, cost:0.40298748, acc:0.8
epoch:100, cost:0.17056146, acc:0.95
epoch:150, cost:0.008562192, acc:1.0
epoch:200, cost:0.00094974303, acc:1.0
epoch:250, cost:0.00044708018, acc:1.0


In [77]:
# https://insightcampus.co.kr/insightcommunity/?mod=document&uid=12936
import numpy as np
import tensorflow as tf
from tensorflow.contrib import rnn
import random
import collections
import time

tf.reset_default_graph()

start_time = time.time()
def elapsed(sec):
    if sec<60:
        return str(sec) + " sec"
    elif sec<(60*60):
        return str(sec/60) + " min"
    else:
        return str(sec/(60*60)) + " hr"


## tensorboard
# Target log path
logs_path = 'log_dir/tmp/tensorflow/rnn_words'
writer = tf.summary.FileWriter(logs_path)

# Text file containing words for training
training_file = 'data/belling_the_cat.txt'

def read_data(fname):
    with open(fname) as f:
        content = f.readlines()
    content = [x.strip() for x in content]
    content = [word for i in range(len(content)) for word in content[i].split()]
    content = np.array(content)
    
    return content

training_data = read_data(training_file)
print("Loaded training data...")

# 단어+숫자 => 딕트로
def build_dataset(words):
    count = collections.Counter(words).most_common()
    dictionary = dict()
    for word, _ in count:
        dictionary[word] = len(dictionary)

    reverse_dictionary = dict(zip(dictionary.values(), dictionary.keys()))
    return dictionary, reverse_dictionary

dictionary, reverse_dictionary = build_dataset(training_data)
vocab_size = len(dictionary) ## 112개

# Parameters
learning_rate = 0.001
training_iters = 50000
display_step = 1000
n_input = 3

# number of units in RNN cell
n_hidden = 512

# tf Graph input
x = tf.placeholder("float", [None, n_input, 1])
y = tf.placeholder("float", [None, vocab_size])

# RNN output node weights and biases
weights = {
    'out': tf.Variable(tf.random_normal([n_hidden, vocab_size]))
}
biases = {
    'out': tf.Variable(tf.random_normal([vocab_size]))
}

def RNN(x, weights, biases):

    # reshape to [1, n_input]
    x = tf.reshape(x, [-1, n_input])

    # Generate a n_input-element sequence of inputs
    # (eg. [had] [a] [general] -> [20] [6] [33])
    x = tf.split(x,n_input,1)

    # 2-layer LSTM, each layer has n_hidden units.
    # Average Accuracy= 95.20% at 50k iter
    rnn_cell = rnn.MultiRNNCell([rnn.BasicLSTMCell(n_hidden),rnn.BasicLSTMCell(n_hidden)])

    # 1-layer LSTM with n_hidden units but with lower accuracy.
    # Average Accuracy= 90.60% 50k iter
    # Uncomment line below to test but comment out the 2-layer rnn.MultiRNNCell above
    # rnn_cell = rnn.BasicLSTMCell(n_hidden)

    # generate prediction
    outputs, states = rnn.static_rnn(rnn_cell, x, dtype=tf.float32)

    # there are n_input outputs but
    # we only want the last output
    return tf.matmul(outputs[-1], weights['out']) + biases['out']

pred = RNN(x, weights, biases)

# Loss and optimizer
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=pred, labels=y))
optimizer = tf.train.RMSPropOptimizer(learning_rate=learning_rate).minimize(cost)

# Model evaluation
correct_pred = tf.equal(tf.argmax(pred,1), tf.argmax(y,1))
accuracy = tf.reduce_mean(tf.cast(correct_pred, tf.float32))

# Initializing the variables
init = tf.global_variables_initializer()

# Launch the graph
with tf.Session() as session:
    session.run(init)
    step = 0
    offset = random.randint(0,n_input+1)
    end_offset = n_input + 1
    acc_total = 0
    loss_total = 0

    writer.add_graph(session.graph)

    while step < training_iters:
        # Generate a minibatch. Add some randomness on selection process.
        if offset > (len(training_data)-end_offset):
            offset = random.randint(0, n_input+1)

        symbols_in_keys = [ [dictionary[ str(training_data[i])]] for i in range(offset, offset+n_input) ]
        symbols_in_keys = np.reshape(np.array(symbols_in_keys), [-1, n_input, 1])

        symbols_out_onehot = np.zeros([vocab_size], dtype=float)
        symbols_out_onehot[dictionary[str(training_data[offset+n_input])]] = 1.0
        symbols_out_onehot = np.reshape(symbols_out_onehot,[1,-1])

        _, acc, loss, onehot_pred = session.run([optimizer, accuracy, cost, pred], \
                                                feed_dict={x: symbols_in_keys, y: symbols_out_onehot})
        loss_total += loss
        acc_total += acc
        if (step+1) % display_step == 0:
            print("Iter= " + str(step+1) + ", Average Loss= " + \
                  "{:.6f}".format(loss_total/display_step) + ", Average Accuracy= " + \
                  "{:.2f}%".format(100*acc_total/display_step))
            acc_total = 0
            loss_total = 0
            symbols_in = [training_data[i] for i in range(offset, offset + n_input)]
            symbols_out = training_data[offset + n_input]
            symbols_out_pred = reverse_dictionary[int(tf.argmax(onehot_pred, 1).eval())]
            print("%s - [%s] vs [%s]" % (symbols_in,symbols_out,symbols_out_pred))
        step += 1
        offset += (n_input+1)
    print("Optimization Finished!")
    print("Elapsed time: ", elapsed(time.time() - start_time))
    print("Run on command line.")
    print("\ttensorboard --logdir=%s" % (logs_path))
    print("Point your web browser to: http://localhost:6006/")
    while True:
        prompt = "%s words: " % n_input
        sentence = input(prompt)
        sentence = sentence.strip()
        words = sentence.split(' ')
        if len(words) != n_input:
            continue
        try:
            symbols_in_keys = [dictionary[str(words[i])] for i in range(len(words))]
            for i in range(32):
                keys = np.reshape(np.array(symbols_in_keys), [-1, n_input, 1])
                onehot_pred = session.run(pred, feed_dict={x: keys})
                onehot_pred_index = int(tf.argmax(onehot_pred, 1).eval())
                sentence = "%s %s" % (sentence,reverse_dictionary[onehot_pred_index])
                symbols_in_keys = symbols_in_keys[1:]
                symbols_in_keys.append(onehot_pred_index)
            print(sentence)
        except:
            print("Word not in dictionary")

Loaded training data...
Iter= 1000, Average Loss= 4.488728, Average Accuracy= 4.40%
['at', 'one', 'another'] - [and] vs [well]
Iter= 2000, Average Loss= 3.019604, Average Accuracy= 17.60%
['is', 'all', 'very'] - [well] vs [with]
Iter= 3000, Average Loss= 2.461506, Average Accuracy= 35.70%
['this', 'proposal', 'met'] - [with] vs [know]
Iter= 4000, Average Loss= 2.308940, Average Accuracy= 42.10%
['by', 'this', 'means'] - [we] vs [we]
Iter= 5000, Average Loss= 1.670886, Average Accuracy= 55.40%
['propose', 'that', 'a'] - [small] vs [it]
Iter= 6000, Average Loss= 1.695166, Average Accuracy= 56.40%
['some', 'signal', 'of'] - [her] vs [danger]
Iter= 7000, Average Loss= 1.427479, Average Accuracy= 62.40%
['we', 'could', 'receive'] - [some] vs [some]
Iter= 8000, Average Loss= 1.302992, Average Accuracy= 66.10%
['.', 'now', ','] - [if] vs [if]
Iter= 9000, Average Loss= 1.174871, Average Accuracy= 65.30%
['meet', 'the', 'case'] - [.] vs [.]
Iter= 10000, Average Loss= 1.050619, Average Accuracy=

KeyboardInterrupt: Interrupted by user